tinyMCE.addI18n('en.imgupload_dlg',{
	ajax_timeout: 'Server Error: AJAX Call Timed Out',
	ajax_failure: 'Server Error',
	dest_dir_not_exist: 'Destination Directory does Not Exist',
	dest_dir_not_set: 'Destination Directory Not Defined',
	dest_dir_not_writable: 'Destination directory not writable',
	dest_file_exists: 'Destination File Exists',
	dest_file_not_exist: 'Destination File Does Not Exist',
	dest_file_not_overwritable: 'Destination File Exists and is NOT Over-Writable',
	failure: 'Failure',
	file_move_finished: 'Finished',
	file_move_failed: 'Failed to move uploaded file',
	illegal_command: 'Illegal Command',
	illegal_file_type: 'Illegal File Type',
	no_dest_dir: 'Destination path directory does not exist',
	no_dest_fname: 'destination file name not set',
	no_upload_file: 'No Upload File Specified or Sent',
	no_upload_file_name:'No File Name',
	replace: 'Replace',
	select_file_msg: 'Please Select File to Upload',
	success: 'Success',
	title: 'Upload Image File',
	upload: 'Upload',
	upload_error: 'Upload Error',
	uploading: 'Upload in Progress',
});
